baseURL = "https://xylemlitmag.netlify.app"
googleAnalytics = ""
theme = "omega"
title = "Xylem Literary Magazine"
[markup.goldmark.renderer]
unsafe = true
[params]
author = "Themefisher"
contact_info = "1001 Brickell bay <br>Dr. Miami, <br>FL 33131"
description = "This is meta description"
logo = "/images/xylemlogo.png"
logo_width = "120px"
preloader = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"
map_center_lat = "25.773606"
map_center_lng = "-80.732655"
map_marker = "images/map-marker.png"
map_position_lat = "25.7635916"
map_position_lng = "-80.1937595"
[[params.social]]
icon = "fa-facebook"
link = "https://www.facebook.com/xylemlitmag/"
title = "facebook"
[[params.social]]
icon = "fa-instagram"
link = "https://www.instagram.com/xylemlitmag"
title = "instagram"
